### PR TITLE
transferred state to mobx

### PR DESCRIPTION
**Pull request by kirkdrichardson**
## Summary of changes
- ejected from create-react-app
- created 3 stores
    - two for each component with state (MortgageComparison & LoanAmountDetails)
    - a root store to pass data between components (loanAmount, e.g. existed in state in both  components)
- reworked components & their methods to fit

This is my first time working with mobx, so a review is probably in order. Everything seems to work, however there are some discrepancies between the calculated values between this mobx version and the original, setState version. From what I can tell, it seems the setState version lagged in updating some of the values across components. Modifying the house cost, e.g., wouldn't immediately pass changed props into the `LoanDetails` component.

I think this is due to `setState` being called without callbacks for subsequent code reliant on the change in state, e.g.:
```
// from the MorgageComparison component

  updateMortgageIntRate = (mortId, newIntRate) => {
    var newState = { intRates: this.state.intRates }
    newState["intRates"][mortId] = newIntRate/100

    this.setState(newState)
    this.recalcMortgages()
  }
```

rather than

```
  updateMortgageIntRate = (mortId, newIntRate) => {
    var newState = { intRates: this.state.intRates }
    newState["intRates"][mortId] = newIntRate/100

    this.setState(newState, this.recalcMortgages)
  
  }
```

However, I didn't fully trace these down since I was focusing on keeping this commit as clean as possible. 

Either way, we should deep dive into making sure these numbers are correct in this mobx version and/or in the setState version

### CODE REVIEW

**Comment by rschultheis** [comment]
can we split this up into two PRs:
- one for eject react app
- one to do mobx?

its a lot of changes here and would prefer to separate the automated ones from the hand coded ones.

**Comment by rschultheis** [comment]
hey @kirkdrichardson so we've updated master a few times, including doing the eject.  Best to re-submit this after merging in.  Sorry for jumping you on the eject but we needed to do it to add tests and travis CI last night.

You may want to consider using the main repo with a branch for PRs, like the other closed PRs.  Slack me if you dont know what I mean.  The way you are doing it with a fork is fine, buts its a bit less legwork in my opinion to use a branch model when everyone knows each other.

**Comment by kirkdrichardson** [comment]
@rschultheis 
no worries, I'll modify the PR & ditch the fork. It'll take me a few days to get to this, but I'll figure it out.

**Comment by rschultheis** [comment]
make a new one if ya want @kirkdrichardson :) .  cleaning up

**Pull request closed without merging**
